apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kube-bookstore
  name: kube-bookstore
spec:
  containers:
    - image: nsivaram90/kubebookstore
      name: kube-bookstore
